version: '3.8'

services:
  gaming-marketplace:
    image: nginx:alpine
    container_name: gaming-marketplace
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    restart: unless-stopped
    networks:
      - gaming-network

  # Optional: Add a reverse proxy for multiple services
  # nginx-proxy:
  #   image: nginxproxy/nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./certs:/etc/nginx/certs
  #   restart: unless-stopped

networks:
  gaming-network:
    driver: bridge